import { NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';
import nodemailer from 'nodemailer';
import fs from 'fs';
import path from 'path';

// Initialize Stripe lazily to avoid build-time issues
function getStripeInstance() {
  const stripeKey = process.env.STRIPE_SECRET_KEY;
  if (!stripeKey) {
    throw new Error('STRIPE_SECRET_KEY is not configured');
  }
  return new Stripe(stripeKey, {
    apiVersion: '2025-09-30.clover',
  });
}

// Handle successful payment
async function handleSuccessfulPayment(paymentIntent: any, orderData: any) {
  const { customerName, customerEmail, customerWebsite, customerPhone, amount, product, licenseQuantity, extendedSupport } = orderData;
  
  // Generate unique order ID
  const orderId = `NMI-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

  // Create transporter for sending emails
  const transporter = nodemailer.createTransport({
    host: 'mail.smartwebrowse.com',
    port: 465,
    secure: true,
    auth: {
      user: process.env.EMAIL_USER || 'noreply@smartwebrowse.com',
      pass: process.env.EMAIL_PASS || 'your-email-password',
    },
  });

  // Send admin notification email
  try {
    const adminMailOptions = {
      from: process.env.EMAIL_USER,
      to: 'nmi-support@smartwebrowse.com',
      subject: `🔔 New Plugin Order #${orderId} - ${customerName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px;">
            🎉 New Plugin Purchase
          </h2>
          
          <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #1f2937; margin-top: 0;">Order Details</h3>
            <p><strong>Order ID:</strong> <code style="background-color: #e5e7eb; padding: 2px 6px; border-radius: 4px;">${orderId}</code></p>
            <p><strong>Product:</strong> Network Merchants Inc Gateway for WooCommerce</p>
            <p><strong>Licenses:</strong> ${licenseQuantity} (${licenseQuantity > 1 ? 'licenses' : 'license'})</p>
            <p><strong>Extended Support:</strong> ${extendedSupport ? 'Yes - 12 months' : 'No - 6 months (included)'}</p>
            <p><strong>Amount:</strong> $${amount}</p>
            <p><strong>Payment Status:</strong> <span style="color: #10b981; font-weight: bold;">✓ Succeeded</span></p>
            <p><strong>Stripe Payment ID:</strong> <code style="background-color: #e5e7eb; padding: 2px 6px; border-radius: 4px;">${paymentIntent.id}</code></p>
          </div>

          <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #1f2937; margin-top: 0;">Customer Information</h3>
            <p><strong>Name:</strong> ${customerName}</p>
            <p><strong>Email:</strong> <a href="mailto:${customerEmail}">${customerEmail}</a></p>
            <p><strong>Website:</strong> ${customerWebsite || 'Not provided'}</p>
            ${customerPhone ? `<p><strong>Phone:</strong> ${customerPhone}</p>` : ''}
          </div>

          <div style="background-color: #f0fdf4; padding: 15px; border-left: 4px solid #10b981; margin: 20px 0;">
            <p style="margin: 0;"><strong>✅ Automated Delivery:</strong> Plugin ZIP file and PDF documentation have been automatically attached to the customer confirmation email sent to <strong>${customerEmail}</strong></p>
          </div>

          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280;">
            <p>This email was automatically generated by the NMI Plugin checkout system.</p>
            <p>Time: ${new Date().toLocaleString()}</p>
          </div>
        </div>
      `,
    };

    await transporter.sendMail(adminMailOptions);
    console.log('Admin notification email sent successfully');
  } catch (emailError) {
    console.error('Failed to send admin notification email:', emailError);
  }

  // Send confirmation email to customer with attachments
  try {
    // Prepare file attachments
    const attachments = [];
    
    // Add plugin ZIP file
    const pluginZipPath = path.join(process.cwd(), 'public', 'network-merchants-inc-gateway-for-woocommerce-1.0.1-clean.zip');
    if (fs.existsSync(pluginZipPath)) {
      attachments.push({
        filename: 'Network-Merchants-Inc-Gateway-for-WooCommerce.zip',
        content: fs.readFileSync(pluginZipPath),
        contentType: 'application/zip'
      });
    }
    
    // Add PDF documentation
    const pdfPath = path.join(process.cwd(), 'public', 'docs', 'Installation & Setup Guide for NMI Payment Gateway Plugin.pdf');
    if (fs.existsSync(pdfPath)) {
      attachments.push({
        filename: 'Installation & Setup Guide for NMI Payment Gateway Plugin.pdf',
        content: fs.readFileSync(pdfPath),
        contentType: 'application/pdf'
      });
    }

    const customerMailOptions = {
      from: `"Smartwebrowse India Private Limited" <${process.env.EMAIL_USER}>`,
      to: customerEmail,
      subject: `🎉 Your NMI Plugin Order Confirmation #${orderId}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;">
            <h1 style="color: white; margin: 0; font-size: 28px;">Thank You for Your Purchase! 🎉</h1>
          </div>

          <div style="background-color: #f9fafb; padding: 25px; border-radius: 10px; margin-bottom: 20px;">
            <h2 style="color: #1f2937; margin-top: 0;">Order Confirmed</h2>
            <p>Hello <strong>${customerName}</strong>,</p>
            <p>Your order has been successfully processed! Your plugin files and documentation are attached to this email.</p>
          </div>

          <div style="background-color: #eff6ff; border-left: 4px solid #3b82f6; padding: 20px; margin: 20px 0;">
            <h3 style="color: #1e40af; margin-top: 0;">📦 Order Summary</h3>
            <p><strong>Order ID:</strong> <code style="background: white; padding: 4px 8px; border-radius: 4px;">${orderId}</code></p>
            <p><strong>Product:</strong> Network Merchants Inc Gateway for WooCommerce</p>
            <p><strong>Licenses:</strong> ${licenseQuantity} (${licenseQuantity > 1 ? 'licenses' : 'license'})</p>
            <p><strong>Extended Support:</strong> ${extendedSupport ? 'Yes - 12 months of expert support' : 'No - 6 months included'}</p>
            <p><strong>Total Paid:</strong> <strong style="color: #059669; font-size: 20px;">$${amount}</strong></p>
          </div>

          <div style="background-color: #f0fdf4; border-left: 4px solid #10b981; padding: 20px; margin: 20px 0;">
            <h3 style="color: #065f46; margin-top: 0;">📎 Attachments Included</h3>
            <p>✅ <strong>Plugin ZIP File:</strong> Network-Merchants-Inc-Gateway-for-WooCommerce.zip</p>
            <p>✅ <strong>Installation Guide:</strong> Installation & Setup Guide for NMI Payment Gateway Plugin.pdf</p>
            <p style="margin-top: 15px; font-weight: bold; color: #047857;">Everything you need is attached to this email!</p>
          </div>

          <div style="background-color: #fff7ed; border-left: 4px solid #f59e0b; padding: 20px; margin: 20px 0;">
            <h3 style="color: #92400e; margin-top: 0;">💡 Need Help?</h3>
            <p>If you have any questions or need assistance, our support team is here to help!</p>
            <p>📧 Email: <a href="mailto:nmi-support@smartwebrowse.com">nmi-support@smartwebrowse.com</a></p>
            <p>⏰ Response Time: Within 12 hours</p>
          </div>

          <div style="margin-top: 30px; padding: 20px; background-color: #f9fafb; border-radius: 10px; text-align: center;">
            <p style="color: #6b7280; margin: 0; font-size: 14px;">
              This is an automated confirmation email.<br>
              © ${new Date().getFullYear()} Smartwebrowse India Private Limited. All rights reserved.
            </p>
          </div>
        </div>
      `,
      attachments: attachments,
    };

    await transporter.sendMail(customerMailOptions);
    console.log('Customer confirmation email sent successfully');
  } catch (emailError) {
    console.error('Failed to send customer confirmation email:', emailError);
  }

  return NextResponse.json({
    success: true,
    orderId,
    paymentIntentId: paymentIntent.id,
    message: 'Payment successful',
  });
}

export async function POST(request: NextRequest) {
  try {
    const {
      paymentMethodId,
      customerName,
      customerEmail,
      customerWebsite,
      customerPhone,
      amount,
      product,
      licenseQuantity,
      extendedSupport,
    } = await request.json();

    // Validate input
    if (!paymentMethodId || !customerEmail || !customerName) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Create payment intent
    const stripe = getStripeInstance();
    console.log('Creating payment intent with amount:', amount * 100, 'cents');
    console.log('Payment method ID:', paymentMethodId);
    
    const paymentIntent = await stripe.paymentIntents.create({
      amount: amount * 100, // Convert to cents
      currency: 'usd',
      payment_method: paymentMethodId,
      confirm: true,
      return_url: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://www.smartwebrowse.com'}/thank-you/nmi-purchase`,
      description: product,
      metadata: {
        customer_name: customerName,
        customer_email: customerEmail,
        customer_website: customerWebsite || '',
        customer_phone: customerPhone || '',
        product: product,
        license_quantity: licenseQuantity,
        extended_support: extendedSupport ? 'Yes' : 'No',
      },
    });

    console.log('Payment intent created:', paymentIntent.id, 'Status:', paymentIntent.status);

    // Handle different payment intent statuses
    if (paymentIntent.status === 'succeeded') {
      // Payment succeeded immediately
      console.log('Payment succeeded immediately');
      return await handleSuccessfulPayment(paymentIntent, {
        customerName,
        customerEmail,
        customerWebsite,
        customerPhone,
        amount,
        product,
        licenseQuantity,
        extendedSupport,
      });
    } else if (paymentIntent.status === 'requires_action') {
      // Payment requires additional authentication (3D Secure)
      console.log('Payment requires additional authentication');
      return NextResponse.json({
        success: false,
        error: 'Payment requires additional authentication',
        requires_action: true,
        payment_intent_id: paymentIntent.id,
      }, { status: 400 });
    } else {
      // Payment failed or other status
      console.log('Payment failed with status:', paymentIntent.status);
      return NextResponse.json({
        success: false,
        error: `Payment failed: ${paymentIntent.status}`,
        payment_intent_id: paymentIntent.id,
      }, { status: 400 });
    }
  } catch (error: any) {
    console.error('Payment processing error:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Payment processing failed' },
      { status: 500 }
    );
  }
}